name: test
channels:
  - conda-forge
  - defaults

dependencies:
    # Base depends
  - python
  - numpy
  - cython
  - eigen
  - igraph
  - scipy
  - scikit-image
  - matplotlib
  - opencv
  - Pillow
  - pandas
  - gsd
  - python-igraph
  - cmake
  - freud
  - ipywidgets

    # Testing
  - pytest
